name: create-snake
on:
  workflow_dispatch:
  schedule:
    - cron: "0 15 * * *"

  push:
    branches:
    - main

permissions: 
  contents: write

jobs:
  update-repository:
    name: Actualiza README
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Generador Snake SVG
        uses: Platane/snk@v3
        id: snake-svg
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/snake_satoru.svg
            dist/snake_dark_satoru.svg?palette=github-dark

      - name: push to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.SATORU }}